### ISSUE TITLE
multiprocessing error on machsmt_build

### ISSUE THREAD

**Issue by j29scott** [j29scott/MachSMT#2]
```fmora@MacBook-Pro medley-solver % machsmt_build -f machsmttrain.csv -l tmp
Trying to load existing database.
[machsmt] warning: No DB found. Will attempt to produce a new one. 
Indexing Input Files |################################| 4/4
Parsing Benchmark FilesTraceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/machsmt-0.3-py3.8.egg/EGG-INFO/scripts/machsmt_build", line 18, in <module>
  File "/usr/local/lib/python3.8/site-packages/machsmt-0.3-py3.8.egg/EGG-INFO/scripts/machsmt_build", line 12, in main
  File "/usr/local/lib/python3.8/site-packages/machsmt-0.3-py3.8.egg/machsmt/db/db.py", line 148, in build
    with Pool(processes=settings.cores) as pool:
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 212, in _init_
    self._repopulate_pool()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in _init_
    super().__init__(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in _init_
    self._launch(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 183, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
AttributeError: module '_main_' has no attribute '_spec_'
/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py(183)get_preparation_data()```

**Comment by j29scott** [comment]
Bug found by Fed Mora

I'll check in his csv
